version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  # Adjust if your Next.js project is in a subfolder like /frontend
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "npm"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/mcp-nexus"  # adjust to your Python package folder
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "pip"
      include: "scope"

  # If using Poetry, replace above with:
  # - package-ecosystem: "poetry"
  #   directory: "/mcp-nexus"
  #   schedule:
  #     interval: "weekly"
  #   labels:
  #     - "dependencies"
  #     - "python"
